### ISSUE TITLE
Data for reproducing figure 3

### ISSUE THREAD

**Issue by neworderofjamie** [INM-6/multi-area-model#12]
I'm trying to get hold of the data to reproduce figure 3 (resting state with coupling constant = 1) but the [gnode repository](https://gin.g-node.org/maximilian.schmidt/multi-area-model-data) doesn't appear to mention figure 3 at all and the data for the [most similar looking simulation](https://gin.g-node.org/maximilian.schmidt/multi-area-model-data/src/master/533d73357fbe99f6178029e6054b571b485f40f6) only includes what I'm guessing are mean firing rates for each area which is insufficient.

Thanks in advance for your help!

**Comment by jarsi** [comment]
Hi!

Indeed, the table is not mentioning figure 3 at all, thanks for pointing this out. I think you might be looking for the [data with simulation label 33fb5955558ba8bb15a3fdce49dfd914682ef3ea](https://gin.g-node.org/maximilian.schmidt/multi-area-model-data/src/master/33fb5955558ba8bb15a3fdce49dfd914682ef3ea). This is the data that is loaded in the plotting script if one requests the usage of the [original data](https://github.com/INM-6/multi-area-model/blob/f6012ceda4c89427dd31869f1a1e8218d03a8ea9/figures/Schmidt2018_dyn/Fig3_ground_state_chi1.py#L90). 

This data is also in agreement with the columnar descriptions given in the table of the [gnode repository](https://gin.g-node.org/maximilian.schmidt/multi-area-model-data). For Figure 3 all properties described in the section "Refinement of connectivity by dynamical constraints" of the paper apply. Thus the data is "after stabilization" and has an increased external input onto population 5E and 6E equal to 1.125. Furthermore the coupling constant equals 1 as the figure deals with the ground state.

I hope this helps, Cheers.

**Comment by mschmidt87** [comment]
Thank you @neworderofjamie for reporting this. @jarsi is absolutely right and already created a PR to fix the README (https://gin.g-node.org/maximilian.schmidt/multi-area-model-data/pulls/1#issuecomment-281), which I just merged. 

The README should now be correct: https://gin.g-node.org/maximilian.schmidt/multi-area-model-data

Therefore closing this issue. If anything else is unclear, please reopen or create another issue, @neworderofjamie .

**Comment by neworderofjamie** [comment]
Thank you so much for your prompt response guys!
