### ISSUE TITLE
NEST compilation issues in connection with conda environment

### ISSUE THREAD

**Issue by mschmidt87** [INM-6/multi-area-model#2]
This issue deal with our compilation problems with NEST and the conda environment. This is our current status of knowledge:

We found two different solutions for the simulations on the one hand and mean-field theory calculation on the other hand:

**Simulations**

Deactivate conda environment, execute cmake with explicite python paths of the conda environment.

**MFT**

Activate conda environment and compile NEST inside this conda environment, but without MPI, OpenMP, readline and ncurses, with such a cmake line:

`cmake -Dwith-gsl=$HOME/miniconda3/envs/multiarea_model -Dwith-readline=OFF -Dwith-ltdl=OFF -Dwith-openmp=OFF -DCMAKE_INSTALL_PREFIX:PATH=$HOME/nest-2.14.0-conda-mam `

For your interest: @AlexVanMeegen , @albada , @heplesser, @jougs, @terhorstd

**Comment by AlexVanMeegen** [comment]
Looks like it was caused by an issue in the `siegert_neuron`, [#1059 of the NEST repository](https://github.com/nest/nest-simulator/pull/1059) fixes it for me.
