### ISSUE TITLE
Is "for 'i' in target_pop" an error in this code occured in Model.py

### ISSUE THREAD

**Issue by lepodl** [INM-6/multi-area-model#26]
```python
 for target_area, source_area in product(area_list, area_list):
        if source_area != target_area:
            for target_pop, source_pop in product(population_list, population_list):
                if 'I' in target_pop:
                    synapse_weights_mean[target_area][target_pop][
                        source_area][source_pop] *= cc_weights_I_factor
                    synapse_weights_sd[target_area][target_pop][
                        source_area][source_pop] *= cc_weights_I_factor
```
Is "for 'i' in target_pop" an error in this code in Model.py? Inhibitory weights are enhanced by factor cc_weights_I_factor, but you choose the inhibitory target_pop as maniuplating object.

**Comment by AlexVanMeegen** [comment]
Hey @lepodl,

Thanks for reporting here! As far as I can see, the implementation is consistent with the desired behavior. From the second-to-last paragraph of the materials and methods section in ([Schmidt et al. 2018](https://journals.plos.org/ploscompbiol/article?id=10.1371/journal.pcbi.1006359#sec002)): "Therefore, we introduce two factors `chi` and `chi_I` to scale the weight of synapses onto excitatory neurons by `chi` and **onto** inhibitory neurons by `chi_I` [emphasis added]."

In the above code, `cc_weights_I_factor` is precisely this factor `chi_I`. Do you agree that the implementation is consistent with the manuscript or am I missing something here? Maybe it is important to mention here that a small fraction of cortico-cortical projections in the model target inhibitory neurons.


Cheers,
Alex


PS: Larger blocks of code can be enclosed by ``` to make them better legible, see e.g. [here](https://guides.github.com/features/mastering-markdown/#GitHub-flavored-markdown).

**Comment by mschmidt87** [comment]
Hi, I agree with @AlexVanMeegen , I think the implementation is in line with the manuscript.
To make the code snippet more readable, I edited @lepodl 's comment to add syntax highlighting and proper code formatting.

**Comment by lepodl** [comment]
Okay, it looks like I made a mistake, thank you！！

**Comment by AlexVanMeegen** [comment]
Most welcome! Thanks again for reporting, certainly better to double check than having a bug. I'll go ahead and close the issue.
