### ISSUE TITLE
Some confusion in plotting figures

### ISSUE THREAD

**Issue by BarryLiu97** [INM-6/multi-area-model#27]
Hi, I was trying to implement the [Fig5](https://github.com/INM-6/multi-area-model/blob/master/figures/Schmidt2018_dyn/Fig5_ground_state.py), so I downloaded the data from [here](https://web.gin.g-node.org/maximilian.schmidt/multi-area-model-data), and define the variable `original_data_path` in `config.py'. 
![image](https://user-images.githubusercontent.com/65115609/114835883-a037c780-9e04-11eb-8566-781167a5b246.png)
However, when I run the [code](https://github.com/INM-6/multi-area-model/blob/master/figures/Schmidt2018_dyn/Fig5_ground_state.py), I've got an error:
```
TypeError: Not supported. Please store the matrix in a binary numpy file and define the path to the file as the parameter value
```
The error coms from the line 107 ```M = MultiAreaModel({})```
The OS is ubuntu cluster.

**Comment by jarsi** [comment]
Hi,
the error arises in this [line](https://github.com/INM-6/multi-area-model/blob/2583232586d235594854842cb9a92a620ba2c93a/multiarea_model/multiarea_model.py#L138). Line [135](https://github.com/INM-6/multi-area-model/blob/2583232586d235594854842cb9a92a620ba2c93a/multiarea_model/multiarea_model.py#L135) checks whether `K_stable is None`. The way that the multi-area model is instantiated in the [figure 5 code](https://github.com/INM-6/multi-area-model/blob/master/figures/Schmidt2018_dyn/Fig5_ground_state.py), this if clause should hold `True`. You pass an empty dict, thus the parameters should be taken from the `default_params.py` file. K_stable is defined [here](https://github.com/INM-6/multi-area-model/blob/2583232586d235594854842cb9a92a620ba2c93a/multiarea_model/default_params.py#L124), and it is set to `None` by default. There has previously been an error, it used to be set to `False`, see this [commit](https://github.com/INM-6/multi-area-model/commit/a6b7ecb2ef43052e6ac93cc88678ceeeabcbe117).

Is your code up to date, what is the default value for K_stable for you?

**Comment by BarryLiu97** [comment]
Hi,
The value of K_stable in the ```default_params.py``` is None.
![image](https://user-images.githubusercontent.com/65115609/114897465-d6e10280-9e43-11eb-8440-e75707ec94e5.png)

**Comment by BarryLiu97** [comment]
Sorry, I just found the version I used , the value of K_stable is False

**Comment by jarsi** [comment]
No worries, glad I could help. Can I close this issue?

**Comment by BarryLiu97** [comment]
Absolutely.
