### ISSUE TITLE
Cannot find reference 'sort_membrane_by_id' in 'analysis_helpers.py' 

### ISSUE THREAD

**Issue by ChenLumen** [INM-6/multi-area-model#29]
Hi, when I use the analysis.py file, it is indicated on line 162 that there is no such function in analysis_helper.py file.Can I find this function or are there alternatives? Thanks!

**Comment by jarsi** [comment]
Hi,

indeed, this function seems to be missing. We need to look into this. In the meanwhile you can either 
* copy the function from [here](https://github.com/INM-6/correlation-toolbox/blob/26b9e999069990a8b756d8a4d880bd152f95149f/correlation_toolbox/helper.py#L150)
* or install the [correlation-toolbox](https://github.com/INM-6/correlation-toolbox) and access the function via `import correlation_toolbox.helper as ch; ch.sort_membrane_by_id()`.

**Comment by ChenLumen** [comment]
> Hi,
> 
> indeed, this function seems to be missing. We need to look into this. In the meanwhile you can either
> 
> * copy the function from [here](https://github.com/INM-6/correlation-toolbox/blob/26b9e999069990a8b756d8a4d880bd152f95149f/correlation_toolbox/helper.py#L150)
> * or install the [correlation-toolbox](https://github.com/INM-6/correlation-toolbox) and access the function via `import correlation_toolbox.helper as ch; ch.sort_membrane_by_id()`.

Ok, thanks!
